### ISSUE TITLE
Da mobile il menù collassa sul testo

### ISSUE THREAD

**Issue by ghost** [Davi0k/davide.codes#1]
![Screenshot_20201012-143814.png](https://user-images.githubusercontent.com/44380480/95747631-0ba7ad80-0c99-11eb-8a91-cd5902cad835.png)

**Comment by Davi0k** [comment]
Bug causato da alcuni errori nella compatibilità con una parte dei Display Mobile. Risolto sistemando adeguatamente i Breakpoint di Tailwind CSS.
